<script lang="ts">
	import { onMount } from 'svelte';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Dialog from '$lib/components/ui/dialog/index.js';
	import { api, telemetry, type Player } from '$lib/stores/telemetry.svelte.js';
	let search=$state(''), error=$state(''), notice=$state(''), busy=$state(false), input=$state(''), kind=$state('whitelist');
	let lists=$state<{bans:string[];whitelist:string[]}>({bans:[],whitelist:[]});
	let selected=$state<Player|null>(null), action=$state('kick'), reason=$state('Disconnected by an administrator'), modal=$state(false);
	const players=$derived(telemetry.players.filter(p => `${p.name} ${p.uuid}`.toLowerCase().includes(search.toLowerCase())));
	async function load(){try{lists=await api('/lists');}catch(e){error=(e as Error).message;}}
	onMount(load);
	function choose(player:Player, next:string){selected=player;action=next;reason='Disconnected by an administrator';modal=true;error='';}
	async function changeList(which:string,uuid:string,op:string){busy=true;error='';notice='';try{lists=await api(`/lists/${which}`,{method:'POST',body:JSON.stringify({uuid,action:op})});input='';notice=`${which==='bans'?'Ban list':'Whitelist'} updated.`;}catch(e){error=(e as Error).message;}finally{busy=false;}}
	async function confirm(){if(!selected)return;busy=true;error='';try{if(action==='kick'){await api(`/players/${selected.uuid}/kick`,{method:'POST',body:JSON.stringify({reason})});notice=`${selected.name} was disconnected.`;}else{lists=await api('/lists/bans',{method:'POST',body:JSON.stringify({uuid:selected.uuid,action:'add'})});notice=`${selected.name} was banned.`;}modal=false;}catch(e){error=(e as Error).message;}finally{busy=false;}}
</script>
<svelte:head><title>Players | FerrumC Dashboard</title></svelte:head>
<div class="max-w-7xl mx-auto space-y-6">
	{#if error}<p role="alert" class="text-sm text-destructive">{error}</p>{/if}{#if notice}<p role="status" class="text-sm text-success">{notice}</p>{/if}
	<div class="glass rounded-2xl border border-border overflow-hidden">
		<div class="px-6 py-4 border-b border-border bg-secondary/40 flex flex-wrap justify-between items-center gap-4"><div class="flex items-center gap-3"><h2 class="font-semibold">Online Players</h2><span class="rounded-full bg-success/10 px-2 py-0.5 text-sm text-success">{telemetry.players.length}</span></div><Input aria-label="Search players" placeholder="Search name or UUID…" bind:value={search} class="w-full sm:w-64 bg-black/20"/></div>
		<div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-secondary/30 text-muted-foreground"><tr><th class="px-6 py-3 font-medium">Player</th><th class="px-6 py-3 font-medium">UUID</th><th class="px-6 py-3 font-medium text-right">Actions</th></tr></thead><tbody class="divide-y divide-border">
			{#each players as player (player.uuid)}<tr class="hover:bg-secondary/30"><td class="px-6 py-4"><div class="flex items-center gap-3"><span class="size-9 rounded-lg grid place-items-center bg-primary/10 text-primary font-semibold">{player.name.slice(0,2).toUpperCase()}</span><span class="font-medium">{player.name}</span></div></td><td class="px-6 py-4 font-mono text-xs">{player.uuid}</td><td class="px-6 py-4"><div class="flex gap-2 justify-end"><Button size="sm" variant="outline" disabled={busy} onclick={() => changeList('whitelist',player.uuid,'add')}>Whitelist</Button><Button size="sm" variant="outline" disabled={busy} onclick={() => choose(player,'kick')}>Kick</Button><Button size="sm" variant="destructive" disabled={busy} onclick={() => choose(player,'ban')}>Ban</Button></div></td></tr>
			{:else}<tr><td colspan="3" class="p-12 text-center text-muted-foreground">{search?'No matching players.':telemetry.fresh?'No players online. Invite someone to join your Minecraft server.':'The Minecraft server is not online.'}</td></tr>{/each}
		</tbody></table></div>
	</div>
	<div class="glass rounded-2xl border border-border p-6 space-y-5"><div><h2 class="font-semibold">Access Lists</h2><p class="text-sm text-muted-foreground mt-2">Bans persist across restarts. Whitelist changes apply immediately when the whitelist is enabled.</p></div>
		<form class="flex flex-wrap gap-3" onsubmit={(event) => {event.preventDefault();changeList(kind,input,'add');}}><select aria-label="Access list" bind:value={kind} class="rounded-md border border-border bg-secondary px-3 py-2 text-sm"><option value="whitelist">Whitelist</option><option value="bans">Ban list</option></select><Input aria-label="Player UUID" placeholder="Player UUID" bind:value={input} required pattern="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" class="flex-1 min-w-48 font-mono bg-black/20"/><Button type="submit" disabled={busy}>Add player</Button></form>
		<div class="grid md:grid-cols-2 gap-5">{#each [{key:'whitelist' as const,label:'Whitelist'},{key:'bans' as const,label:'Banned Players'}] as list}<section class="rounded-xl border border-border p-4"><h3 class="text-sm font-medium mb-3">{list.label} <span class="text-muted-foreground">({lists[list.key].length})</span></h3><div class="space-y-2">{#each lists[list.key] as identifier}<div class="flex items-center gap-2 justify-between border-b border-border/60 py-2"><span class="font-mono text-xs break-all">{identifier}</span><button class="text-sm text-primary shrink-0 hover:underline disabled:opacity-50" disabled={busy} onclick={() => changeList(list.key,identifier,'remove')}>Remove</button></div>{:else}<p class="text-sm text-muted-foreground py-3">This list is empty.</p>{/each}</div></section>{/each}</div>
	</div>
</div>
<Dialog.Root bind:open={modal}><Dialog.Content class="sm:max-w-md"><Dialog.Header><Dialog.Title>{action==='ban'?'Ban':'Kick'} {selected?.name}?</Dialog.Title><Dialog.Description>{action==='ban'?'This player will be disconnected and blocked from joining until removed from the ban list.':'The player will be disconnected. They can join again.'}</Dialog.Description></Dialog.Header>{#if action==='kick'}<label for="reason" class="text-sm">Disconnect reason</label><Input id="reason" bind:value={reason} maxlength={256}/>{/if}{#if error}<p class="text-sm text-destructive" role="alert">{error}</p>{/if}<div class="flex gap-3 justify-end"><Button variant="outline" disabled={busy} onclick={() => modal=false}>Cancel</Button><Button variant="destructive" disabled={busy} onclick={confirm}>{busy?'Working…':action==='ban'?'Ban player':'Kick player'}</Button></div></Dialog.Content></Dialog.Root>
